### ISSUE TITLE
encounter problems about configuration of running env 

### ISSUE THREAD

**Issue by Fenanxhyy** [talshaharabany/DeepACM2D#1]
the pkg is:
pytorch 1.7.0
torchvision0.8.0
cuda 11.4
ubuntu 18.04

As a green hand, I tried to install neural-renderer-pytorch in many ways but still failed. can anyone share the weights（bing/best/ACM.pt  bing/best/SEG.pt ,or vaihingen's weights is ok）so i can check the "validation", thanks for any help!

btw @talshaharabany @evinpinar

**Comment by FreshManFenan** [comment]
@talshaharabany
